<?xml version="1.0" encoding="utf-8"?>
<TestGroup>
  <Id>Test_820</Id>
  <Description>В проекте допущен ряд ошибок, из-за которых 12 человек из 2081 не может физически эвакуироваться</Description>
  <RegistratorEvacuationTimeMaxDiff>INF</RegistratorEvacuationTimeMaxDiff>
  <RegistratorEvacuatedPeopleCountMaxDiff>INF</RegistratorEvacuatedPeopleCountMaxDiff>
  <ScenarioEvacuationTimeMaxDiff>INF</ScenarioEvacuationTimeMaxDiff>
  <ScenarioEvacuatedPeopleCountMaxDiff>0</ScenarioEvacuatedPeopleCountMaxDiff>
  <ScenarioConcourseTimeMaxDiff>INF</ScenarioConcourseTimeMaxDiff>
  <Tests>
    <Test>
      <Id>Test_820_001</Id>
      <ProjectLocation>FNX-1086.fnx</ProjectLocation>
      <ScenarioName>Сценарий 1</ScenarioName>
      <RegistratorName>Дверь 108</RegistratorName>
      <RegistratorEvacuationTime>0</RegistratorEvacuationTime>
      <RegistratorEvacuatedPeopleCount>0</RegistratorEvacuatedPeopleCount>
      <ScenarioEvacuationTime>0</ScenarioEvacuationTime>
      <ScenarioEvacuatedPeopleCount>2069</ScenarioEvacuatedPeopleCount>
      <ScenarioConcourseTime>0</ScenarioConcourseTime>
    </Test>
  </Tests>
</TestGroup>
